# Generated by Django 4.2 on 2023-05-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='event',
            name='whoRegister',
        ),
    ]
